#工作流名称
name: learn-workflows
on: [push]
jobs:
  #在workflow中使用脚本和环境变量
  using-script-and-env-variables:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
      - name: checkout repository code
        uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: run hello.js
        env:
          MY_PORT: 1234
        run: node hello.js
  using-text-context:
    runs-on: ubuntu-latest
    steps:
      - name: run env
        env:
          MY_PORT: 3301
          MY_NAME: Aurora
         run: echo "${{env.MY_PORT}}----${{env.MY_NAME}}"
      - run: echo "${{github.ref}}"
