#工作流名称
name: learn-workflows
on: [push]
jobs:
  learn:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
      - name: checkout repository code
        uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: run hello.js
        run: node hello.js
